config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  post 'join', to:"events#join_event"
  post 'unjoin', to:"events#unjoin_event"
  resources :users, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :creator, class_name: "User"
  has_many :event_attendings, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendings

  scope :upcoming, -> { where("date >= #{Time.now.day}") }
  scope :past, -> { where("date < #{Time.now.day}") }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord

  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event", foreign_key: "creator_id"
  has_many :event_attendings, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    #add username to sign-up 'table'
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
    #add username to sign-in 'table'
    devise_parameter_sanitizer.permit(:sign_in, keys:[:username])
    #add username to account-update
    devise_parameter_sanitizer.permit(:account_update, keys:[:username])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ActionView::Helpers::DateHelper




  before_action :authenticate_user!, except: [:index, :show]

  

  def index
    @events = Event.all.order("created_at DESC")
    #byebug
  end
  
  def new
    @event = current_user.created_events.new
  end
  
  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      red3irect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def join_event
    @events = Event.all
    @user = current_user
    @event = Event.find(params[:event_id])
    @event.attendees.push(@user) if !@event.attendees.include?(@user)
    render 'index'
  end

  def unjoin_event
    @events = Event.all
    @user = current_user
    @event = Event.find(params[:event_id])

    @user.attended_events.delete(@event)
    @event.attendees.delete(@user)
    render 'index'
  end

  

  private

  def event_params
    params.require(:event).permit(:date, :location, :description)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 


  

  def show
    @user = User.find(params[:id])
    @events = @user.attended_events
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_feed.html.erb
<div class="container text-center">
  <% @events.each do |event| %>
  <% @user = event.creator %>
    <div class="card my-2 mx-auto" style="width: 60%;">
      <div class="card-header"><%= distance_of_time_in_words(event.date, Time.now, include_seconds: true).titleize %> from now</div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to "#{event.location}", event %></h5>
        <p class="card-text"><%= event.description %></p>       
        <% if event.attendees.include?(current_user) %>
          <%= button_to 'Unjoin this event', {action: "unjoin_event", :event_id => event.id, :user_id => @user.id }, class:"btn btn-danger p-3 d-block mx-auto my-2" %>
          <% else %>
          <%= button_to 'Join this event', {action: "join_event", :event_id => event.id, :user_id => @user.id }, class:"btn btn-info p-3 mx-auto d-block my-2" %>
        <% end %>
        <div class="text-right">
          <%= link_to 'Edit', edit_event_path(event), class:"text-white btn btn-warning px-4"  if current_user == event.creator %>
          <%= link_to 'Delete', event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"}, class:"btn btn-danger" if current_user == event.creator %>
        </div>
        <h5 class="text-primary text-right mt-3"> <%= link_to " Currently attending:#{event.attendees.count}", event_path(event), class: "text-right mt-2" %></h5>
      </div>
    </div>

  <% end %>


</div>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.error_notification %>

  <%= f.input :date, as: :datetime%>
  <%= f.input :location %>
  <%= f.input :description %>
  

  <%= f.button :submit, "Enter", class:"btn btn-success px-3 py-2" %>
<% end %>

app/views/events/edit.html.erb
<h1 class="text-dark text-center">Edit Event</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="text-center">
  <%= link_to "Create New Event", new_event_path, class: "d-inline-block btn btn-success new-event-a" %>
</div>
<%=  render 'feed' %>

app/views/events/new.html.erb
<h1 class="text-center text-dark"> Create New Event</h1>
<%= render 'form'%>

app/views/events/show.html.erb
<%= link_to 'Back to Events', events_path, class:"btn btn-info ml-4"%>
<div class="container text-center">
  
  <div class="card my-4">
    <div class="card-header">
      <p><%= @event.date %><p>
      <p class="text-success h3"><%= distance_of_time_in_words(@event.date, Time.now, include_seconds: true).titleize %> from now</p>
      <h6 class="card-info text-info text-right">Created by <%= link_to "#{@event.creator.username}", @event.creator %></h6>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @event.location %></h5>
      <p class="card-text"><%= @event.description %></p>
    </div>
  </div>
  <ul class="text-left list-unstyled">
    <h3 class="text-info">Currently <%= @event.attendees.count %> people attending: </h3>
    <% @event.attendees.each do |attendee| %>
      <li><%= link_to "#{attendee.username}", user_path(attendee) %></li>
    <% end %>
    
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice notification mb-0 bg-success text-white p-2 text-center"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert notification mb-0 bg-danger text-white p-2 text-center"><%= alert %></p>
    <% end %>

    <div class="bg-dark p-3 row mb-3 mx-0">
      <div class="col"></div>
      <div class="col text-center d-flex justify-content-center align-items-center">
        <%= link_to 'Private-Events', '/', class: 'text-white'%>
      </div>
      <div class="col d-flex justify-content-end">
        <% if user_signed_in? %>
          <%= link_to "Profile", user_path(current_user), class:"text-white h5 mx-5 pt-2"%>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: 'btn btn-danger'%>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "p-2 btn btn-secondary mx-2" %>
          <%= link_to "Sign up", new_user_registration_path, class: "p-2 btn btn-success mx-2" %>
        <% end %>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">
  <h1 class="text-center text-primary mr-5 my-5"><%= @user.username %></h1>
  <div class="row border border-primary py-3">
    <div class="container col">
      <ul class="list-unstyled text-left">
        <h3>Upcoming events: <%=  @events.upcoming.count %></h3>
        <% @events.upcoming.each do |event| %>
          <li class="h5 ml-2 text-success"><%= link_to "#{event.location}", event_path(event) %></li>  
        <% end %>
        
      </ul> 
    </div>

    <div class="container col">
      <ul class="list-unstyled text-left">
        <h3>Past events: <%= @events.past.count %></h3>
        <% @events.past.each do |event| %>
          <li class="h5 ml-2 text-success"><%= link_to "#{event.location}", event_path(event) %></li>  
        <% end %>
        
      </ul>
    </div>
  </div>
</div>